### ISSUE TITLE
Better explanation for engine balance

### ISSUE THREAD

**Issue by NyankoSensei** [luketheyeti/YetiSpaceProgram#2]
You want the engine use LFxOX+ElectricCharge or like a nerva LF+ElectricCharge ?
For the Heat that need to be tested ingame because mount section can give troubles with heat production.

**Comment by luketheyeti** [comment]
Yeah I want the engine to use LF+OX+ElectricCharge, when I add it as a third PROPELLANT it doesn't seem to work in game. Can you have 3 Prop types with the liquidfuel enginetype?

**Comment by luketheyeti** [comment]
Ok I have the engine using LFO+Electric charge now, I think I just had some extra spaces somewhere. Works in new upload.
