### ISSUE TITLE
Weight Balance

### ISSUE THREAD

**Issue by NyankoSensei** [luketheyeti/YetiSpaceProgram#3]
For better weight balance keep in mind these values
1 unit of LF, OX, Monoprop or Ore is 5 liters
1 m³ = 1000 Liters = 0.125 T weight
Those are the standard values of ksp if you use them you don't have troubles with gamebalance

**Comment by luketheyeti** [comment]
thanks! Right now I'm just eyeballing it. I've modeled versions of the stock tanks and am using these to compare the size of my parts to the stock parts.
