### ISSUE TITLE
Repository tree

### ISSUE THREAD

**Issue by NyankoSensei** [luketheyeti/YetiSpaceProgram#4]
Is better if you move the main folder inside a GameData Folder

Repo YetiSpaceProgram/GameData/YetiSpaceProgram

That is good for when you make a release, when you unpack the archive you get GameData/YetiSpaceProgram, for those who download is more clearly understand where to install it

**Comment by luketheyeti** [comment]
good catch, thanks!

**Comment by luketheyeti** [comment]
new files uploaded with better structure
